import { createClient } from "@supabase/supabase-js";
  import { verifySiweMessage } from "@worldcoin/minikit-js/siwe";
  import { rateLimit } from "./_rateLimit.mjs";
  import { consumeNonce } from "./nonce.mjs";

  const supabase = createClient(
    process.env.SUPABASE_URL || process.env.VITE_SUPABASE_ANON_KEY || "https://vdenlattnqkfurebyyfz.supabase.co",
    process.env.SUPABASE_SERVICE_ROLE_KEY || ""
  );

  export default async function handler(req, res) {
    res.setHeader("Access-Control-Allow-Origin", "*");
    res.setHeader("Access-Control-Allow-Methods", "POST, GET, OPTIONS");
    res.setHeader("Access-Control-Allow-Headers", "Content-Type, Authorization");
    if (req.method === "OPTIONS") return res.status(200).end();

    if (req.method === "GET") {
      const wallet = req.query?.wallet;
      if (!wallet) return res.status(400).json({ valid: false });
      try {
        const { data } = await supabase
          .from("users")
          .select("*")
          .eq("wallet_address", wallet)
          .maybeSingle();
        return res.status(200).json({
          valid: !!data?.is_verified,
          user: data,
          wallet_address: data?.wallet_address,
        });
      } catch (err) {
        return res.status(200).json({ valid: false });
      }
    }

    if (req.method !== "POST") {
      return res.status(405).json({ success: false, error: "Method not allowed" });
    }

    if (rateLimit(req, { max: 10, windowMs: 60000 }).limited) {
      return res.status(429).json({ success: false, error: "Demasiadas solicitudes." });
    }

    const body = req.body || {};
    const { wallet_address, message, signature, nonce, username, is_orb_verified } = body;

    if (!wallet_address || !nonce) {
      return res.status(400).json({ success: false, error: "Missing wallet_address or nonce" });
    }

    // Verify nonce was generated by our server
    if (!consumeNonce(nonce)) {
      return res.status(400).json({ success: false, error: "Invalid or expired nonce" });
    }

    // If message & signature present, verify SIWE
    if (message && signature) {
      try {
        const verification = await verifySiweMessage(
          { message, signature, address: wallet_address },
          nonce
        );
        if (!verification.isValid) {
          return res.status(400).json({ success: false, error: "SIWE verification failed" });
        }
      } catch (err) {
        console.error("[VERIFY] SIWE error:", err);
        return res.status(400).json({ success: false, error: "SIWE verification error: " + err.message });
      }
    }

    // Must be Orb verified (checked client-side via MiniKit.user.verificationStatus)
    if (!is_orb_verified) {
      return res.status(400).json({ success: false, error: "Orb verification required" });
    }

    try {
      // Check if user already exists
      const { data: existing } = await supabase
        .from("users")
        .select("*")
        .eq("wallet_address", wallet_address)
        .maybeSingle();

      if (existing) {
        // Update last login
        await supabase
          .from("users")
          .update({
            username: username || existing.username,
            updated_at: new Date().toISOString(),
          })
          .eq("wallet_address", wallet_address);

        return res.status(200).json({
          success: true,
          wallet_address: existing.wallet_address,
          reused: true,
        });
      }

      // Create new user
      const { data: newUser, error: insertErr } = await supabase
        .from("users")
        .insert({
          wallet_address,
          username: username || null,
          is_verified: true,
          verification_level: "orb",
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        })
        .select()
        .single();

      if (insertErr) {
        console.error("[VERIFY] Insert error:", insertErr);
        return res.status(500).json({ success: false, error: "Failed to create user" });
      }

      return res.status(200).json({
        success: true,
        wallet_address: newUser.wallet_address,
        new_user: true,
      });
    } catch (err) {
      console.error("[VERIFY] Error:", err);
      return res.status(500).json({ success: false, error: "Server error" });
    }
  }
  